### ISSUE TITLE
Add djlint to the pre-commit hook pipeline

### ISSUE THREAD

**Issue by xmnlab** [xmnlab/djangopoc#8]
example: 

Add to pyproject.toml:

```toml
[tool.djlint]
profile = "django"
indent = 2
max_line_length = 79
extension = "html"
use_gitignore = true
extend_exclude = "docs,build"
ignore = "T003"
```

add to .pre-commit-hook.yaml:
```yaml
    - id: djlint-reformat
      name: djlint-reformat
      entry: djlint --reformat .
      pass_filenames: false
      types_or: [html]
      language: python

    - id: djlint-lint
      name: djlint-lint
      entry: djlint --lint .
      pass_filenames: false
      types_or: [html]
      language: python
```
